SPEED_WALL = -100
SPEED_SCENE_GROUND = -100
SPEED_SCENE_BACKGROUD = -150

GROUND_WIDTH = 360
GROUND_HEIGHT = 112
GROUND_PADDING_POSITION = GROUND_HEIGHT/2
GROUND_START = GROUND_PADDING_POSITION * 5
GROUND_TILES = math.abs(HEIGHTS - HEIGHT)/GROUND_HEIGHT
SPACING_OF_OBSTACLES = 10
GENERATOR_DEFAULT_TIME = 5

JUMP_PLAYER_FORZE = 4000
PLAYER_HITBOX_WIDTH, PLAYER_HITBOX_HEIGHT = 20, 20

logger:info(GROUND_TILES)
